model:
  name: 'pcb_rpp_p6'
  pretrained: True
  load_weights: 'log/pcb_rpp_p6_market1501_trainall/model.pth.tar-20'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip','random_crop','random_erase']
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  save_dir: 'log/pcb_rpp_p6_market1501_trainall'

sampler:
  train_sampler: 'RandomSampler'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0003
  max_epoch: 20
  batch_size: 32
  staged_lr: True
  new_layers: ['parts_avgpool', 'classifier']
  base_lr_mult: 0.1
  lr_scheduler: 'multi_step'
  stepsize: [5,10]
  gamma: 0.1
  print_freq: 20

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: True
  evaluate: True
  eval_freq: 10
  rerank: True
  visactmap: False
